name: wheels
channels:
  - conda-forge
  - defaults
dependencies:
  # Python
  - python=3.10
  - pandas
  - matplotlib

  # R
  - r-base=4.3
  - r-ggplot2
  - r-dplyr
  - r-readr

  # utilidades de entorno
  - pip
