name: Wheel Data Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  analysis:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Python dependencies
        run: pip install pandas

      - name: Run preprocessing
        run: python scripts/process.py

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install R dependencies
        run: |
          Rscript -e 'install.packages(c("ggplot2", "dplyr", "readr"))'

      - name: Run analysis
        run: Rscript scripts/analysis.R

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: revolutions-results
          path: output/
